# Generated by Django 4.2 on 2023-04-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_staff_id_alter_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='staff_id',
            new_name='staffRef',
        ),
    ]
