# Generated by Django 4.2 on 2023-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='m', max_length=254),
        ),
    ]
